# Generated by Django 4.2.18 on 2025-02-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='matricula_basica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGNO', models.IntegerField()),
                ('RBD', models.IntegerField(null=True)),
                ('NOM_RBD', models.CharField(null=True)),
                ('COD_REG_RBD', models.IntegerField(null=True)),
                ('NOM_REG_RBD_A', models.CharField(null=True)),
                ('COD_PRO_RBD', models.IntegerField(null=True)),
                ('COD_COM_RBD', models.IntegerField(null=True)),
                ('NOM_COM_RBD', models.CharField(null=True)),
                ('COD_DEPROV_RBD', models.IntegerField(null=True)),
                ('NOM_DEPROV_RBD', models.CharField(null=True)),
                ('COD_DEPE2', models.IntegerField(null=True)),
                ('RURAL_RBD', models.IntegerField(null=True)),
                ('COD_ENSE2', models.IntegerField(null=True)),
                ('COD_GRADO2', models.IntegerField(null=True)),
                ('MRUN', models.IntegerField(null=True)),
                ('GEN_ALU', models.IntegerField(null=True)),
                ('EDAD_ALU', models.IntegerField(null=True)),
                ('COD_COM_ALU', models.IntegerField(null=True)),
                ('NOM_COM_ALU', models.CharField(null=True)),
                ('ENS', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='matricula_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGNO', models.IntegerField()),
                ('RBD', models.IntegerField(null=True)),
                ('NOM_RBD', models.CharField(null=True)),
                ('COD_REG_RBD', models.IntegerField(null=True)),
                ('NOM_REG_RBD_A', models.CharField(null=True)),
                ('COD_PRO_RBD', models.IntegerField(null=True)),
                ('COD_COM_RBD', models.IntegerField(null=True)),
                ('NOM_COM_RBD', models.CharField(null=True)),
                ('COD_DEPROV_RBD', models.IntegerField(null=True)),
                ('NOM_DEPROV_RBD', models.CharField(null=True)),
                ('COD_DEPE2', models.IntegerField(null=True)),
                ('RURAL_RBD', models.IntegerField(null=True)),
                ('COD_ENSE2', models.IntegerField(null=True)),
                ('COD_GRADO2', models.IntegerField(null=True)),
                ('MRUN', models.IntegerField(null=True)),
                ('GEN_ALU', models.IntegerField(null=True)),
                ('EDAD_ALU', models.IntegerField(null=True)),
                ('COD_COM_ALU', models.IntegerField(null=True)),
                ('NOM_COM_ALU', models.CharField(null=True)),
                ('ENS', models.IntegerField(null=True)),
            ],
        ),
    ]
