# Generated by Django 4.2.18 on 2025-03-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0002_alter_resultados_simce_idps_cod_grupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='matricula_superior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_periodo', models.IntegerField()),
                ('mrun', models.IntegerField()),
                ('gen_alu', models.IntegerField()),
                ('rango_edad', models.CharField()),
                ('tipo_inst_1', models.CharField()),
                ('tipo_inst_2', models.CharField()),
                ('nomb_inst', models.CharField()),
                ('nomb_sede', models.CharField()),
                ('modalidad', models.CharField()),
                ('jornada', models.CharField()),
                ('dur_estudio_carr', models.IntegerField()),
                ('dur_total_carr', models.IntegerField()),
                ('region_sede', models.CharField()),
                ('nivel_global', models.CharField()),
                ('valor_arancel', models.IntegerField()),
                ('area_conocimiento', models.CharField()),
                ('acreditada_carr', models.CharField()),
                ('acreditada_inst', models.CharField()),
                ('nivel_carrera_2', models.CharField()),
                ('anio_ing_carr_ori', models.IntegerField()),
                ('anio_ing_carr_act', models.IntegerField()),
                ('forma_ingreso', models.CharField()),
            ],
        ),
    ]
