# Generated by Django 4.2.18 on 2025-03-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0003_matricula_superior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula_superior',
            name='valor_arancel',
            field=models.IntegerField(null=True),
        ),
    ]
