# Generated by Django 4.2.18 on 2025-03-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0004_alter_matricula_superior_valor_arancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula_superior',
            name='mrun',
            field=models.IntegerField(null=True),
        ),
    ]
