# Generated by Django 4.2.18 on 2025-03-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0005_alter_matricula_superior_mrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='dotacion_docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGNO', models.IntegerField()),
                ('NOM_RBD', models.CharField()),
                ('COD_REG_RBD', models.IntegerField()),
                ('NOM_REG_RBD', models.CharField()),
                ('COD_PRO_RBD', models.IntegerField()),
                ('COD_COM_RBD', models.IntegerField()),
                ('NOM_COM_RBD', models.CharField()),
                ('COD_DEPROV_RBD', models.IntegerField()),
                ('NOM_DEPROV_RBD', models.CharField()),
                ('COD_DEPE', models.IntegerField()),
                ('COD_DEPE2', models.IntegerField()),
                ('RURAL_RBD', models.IntegerField()),
                ('DC_A', models.IntegerField(null=True)),
                ('HH_A', models.IntegerField(null=True)),
                ('DC_UTP', models.IntegerField(null=True)),
                ('HH_UTP', models.IntegerField(null=True)),
                ('DC_PDIR', models.IntegerField(null=True)),
                ('HH_PDIR', models.IntegerField(null=True)),
                ('DC_DIR', models.IntegerField(null=True)),
                ('HH_DIR', models.IntegerField(null=True)),
                ('DC_OES', models.IntegerField(null=True)),
                ('HH_OES', models.IntegerField(null=True)),
                ('DC_OF', models.IntegerField(null=True)),
                ('HH_OF', models.IntegerField(null=True)),
                ('DC_JUTP', models.IntegerField(null=True)),
                ('HH_JUTP', models.IntegerField(null=True)),
                ('DC_IG', models.IntegerField(null=True)),
                ('HH_IG', models.IntegerField(null=True)),
                ('DC_OR', models.IntegerField(null=True)),
                ('HH_OR', models.IntegerField(null=True)),
                ('DC_DIR_SOST', models.IntegerField(null=True)),
                ('HH_DIR_SOST', models.IntegerField(null=True)),
                ('DC_TP_SOST', models.IntegerField(null=True)),
                ('HH_TP_SOST', models.IntegerField(null=True)),
                ('DC_SUP_SOST', models.IntegerField(null=True)),
                ('HH_SUP_SOST', models.IntegerField(null=True)),
                ('DC_JCM_SOST', models.IntegerField(null=True)),
                ('HH_JCM_SOST', models.IntegerField(null=True)),
                ('DC_SUBDIR', models.IntegerField(null=True)),
                ('HH_SUBDIR', models.IntegerField(null=True)),
                ('DC_PROF_ENC', models.IntegerField(null=True)),
                ('HH_PROF_ENC', models.IntegerField(null=True)),
                ('DC_EDUC_TRAD', models.IntegerField(null=True)),
                ('HH_EDUC_TRAD', models.IntegerField(null=True)),
                ('DC_TOT', models.IntegerField(null=True)),
                ('HH_TOT', models.IntegerField(null=True)),
            ],
        ),
    ]
