# Generated by Django 4.2.18 on 2025-03-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0006_dotacion_docente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dotacion_docente',
            old_name='NOM_REG_RBD',
            new_name='NOM_REG_RBD_A',
        ),
        migrations.RemoveField(
            model_name='dotacion_docente',
            name='DC_JCM_SOST',
        ),
        migrations.RemoveField(
            model_name='dotacion_docente',
            name='HH_JCM_SOST',
        ),
    ]
