# Generated by Django 4.2.18 on 2025-03-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0009_alter_rendimiento_academico_prom_gral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimiento_academico',
            name='PROM_GRAL',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
