# Generated by Django 4.2.18 on 2025-04-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0012_alter_rendimiento_academico_sit_fin_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimiento_academico',
            name='PROM_GRAL',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
