from django.db import models


class matricula_parvulo (models.Model):

    agno = models.IntegerField()
    mes = models.IntegerField ()
    mrun = models.IntegerField()
    gen_alu = models.IntegerField()
    id_estab = models.IntegerField()
    nom_estab = models.CharField(max_length= 1000)
    cod_reg_estab = models.IntegerField(null=True)
    cod_pro_estab = models.IntegerField(null=True)
    cod_com_estab = models.IntegerField(null=True)
    nom_reg_estab = models.CharField(max_length=500, null=True)
    nom_reg_a_estab = models.CharField(max_length=20,null=True)
    nom_pro_estab = models.CharField(max_length=200,null=True)
    nom_com_estab = models.CharField(max_length=500,null=True)
    cod_deprov_estab = models.IntegerField(null=True)
    nom_deprov_estab = models.CharField(max_length=200, null=True)
    rural_estab = models.IntegerField(null=True)
    dependencia = models.IntegerField(null=True)
    nivel1 = models.IntegerField(null=True)
    cod_ense1_m = models.IntegerField(null=True)
    cod_ense2_m = models.IntegerField(null=True)

class matricula_basica (models.Model):

    AGNO = models.IntegerField()
    RBD = models.IntegerField(null=True)
    NOM_RBD = models.CharField(null=True)
    COD_REG_RBD = models.IntegerField(null=True)
    NOM_REG_RBD_A = models.CharField(null=True)
    COD_PRO_RBD = models.IntegerField(null=True)
    COD_COM_RBD = models.IntegerField(null=True)
    NOM_COM_RBD = models.CharField(null=True)
    COD_DEPROV_RBD = models.IntegerField(null=True)
    NOM_DEPROV_RBD = models.CharField(null=True)
    COD_DEPE2 = models.IntegerField(null=True)
    RURAL_RBD = models.IntegerField(null=True)
    COD_ENSE2 = models.IntegerField(null=True)
    COD_GRADO2 = models.IntegerField(null=True)
    MRUN = models.IntegerField(null=True)
    GEN_ALU = models.IntegerField(null=True)
    EDAD_ALU = models.IntegerField(null=True)
    COD_COM_ALU = models.IntegerField(null=True)
    NOM_COM_ALU = models.CharField(null=True)
    ENS = models.IntegerField(null=True)
    
class matricula_media (models.Model):

    
    AGNO = models.IntegerField()
    RBD = models.IntegerField(null=True)
    NOM_RBD = models.CharField(null=True)
    COD_REG_RBD = models.IntegerField(null=True)
    NOM_REG_RBD_A = models.CharField(null=True)
    COD_PRO_RBD = models.IntegerField(null=True)
    COD_COM_RBD = models.IntegerField(null=True)
    NOM_COM_RBD = models.CharField(null=True)
    COD_DEPROV_RBD = models.IntegerField(null=True)
    NOM_DEPROV_RBD = models.CharField(null=True)
    COD_DEPE2 = models.IntegerField(null=True)
    RURAL_RBD = models.IntegerField(null=True)
    COD_ENSE2 = models.IntegerField(null=True)
    COD_GRADO2 = models.IntegerField(null=True)
    MRUN = models.IntegerField(null=True)
    GEN_ALU = models.IntegerField(null=True)
    EDAD_ALU = models.IntegerField(null=True)
    COD_COM_ALU = models.IntegerField(null=True)
    NOM_COM_ALU = models.CharField(null=True)
    ENS = models.IntegerField(null=True)

class matricula_superior(models.Model):

    cat_periodo= models.IntegerField()
    mrun= models.IntegerField(null=True)
    gen_alu= models.IntegerField()
    rango_edad= models.CharField()
    tipo_inst_1= models.CharField()
    tipo_inst_2= models.CharField()
    nomb_inst= models.CharField()
    nomb_sede= models.CharField()
    modalidad= models.CharField()
    jornada= models.CharField()
    dur_estudio_carr= models.IntegerField()
    dur_total_carr= models.IntegerField()
    region_sede= models.CharField()
    nivel_global= models.CharField()
    valor_arancel= models.IntegerField(null=True)
    area_conocimiento= models.CharField()
    acreditada_carr= models.CharField()
    acreditada_inst= models.CharField()
    nivel_carrera_2= models.CharField()
    anio_ing_carr_ori= models.IntegerField()
    anio_ing_carr_act= models.IntegerField()
    forma_ingreso= models.CharField()

class resultados_simce(models.Model):

    agno= models.IntegerField()
    grado = models.CharField()
    cod_reg = models.IntegerField()
    nom_reg = models.CharField()
    prom_lect_reg = models.IntegerField()
    prom_mate_reg = models.IntegerField()
    dif_lect_reg = models.IntegerField()
    dif_mate_reg = models.IntegerField()
    sigdif_lect_reg = models.IntegerField()
    sigdif_mate_reg = models.IntegerField()

class resultados_simce_idps(models.Model):

    rbd = models.IntegerField()
    agno = models.IntegerField()
    grado = models.IntegerField()
    ind = models.CharField()
    dim = models.CharField()
    prom = models.IntegerField(null=True)
    nom_rbd = models.CharField()
    cod_reg_rbd = models.IntegerField()
    nom_reg_rbd = models.CharField()
    cod_pro_rbd = models.IntegerField()
    nom_pro_rbd = models.CharField()
    cod_com_rbd = models.IntegerField()
    nom_com_rbd = models.CharField()
    nom_deprov_rbd = models.CharField()
    cod_depe2 = models.IntegerField()
    cod_grupo = models.IntegerField(null=True)
    cod_rural_rbd = models.IntegerField()

class dotacion_docente(models.Model):

    AGNO= models.IntegerField()
    NOM_RBD= models.CharField()
    COD_REG_RBD= models.IntegerField()
    NOM_REG_RBD_A= models.CharField()
    COD_PRO_RBD= models.IntegerField()
    COD_COM_RBD= models.IntegerField()
    NOM_COM_RBD= models.CharField()
    COD_DEPROV_RBD= models.IntegerField()
    NOM_DEPROV_RBD= models.CharField()
    COD_DEPE= models.IntegerField()
    COD_DEPE2= models.IntegerField()
    RURAL_RBD= models.IntegerField()
    DC_A= models.IntegerField(null=True)
    HH_A= models.IntegerField(null=True)
    DC_UTP= models.IntegerField(null=True)
    HH_UTP= models.IntegerField(null=True)
    DC_PDIR= models.IntegerField(null=True)
    HH_PDIR= models.IntegerField(null=True)
    DC_DIR= models.IntegerField(null=True)
    HH_DIR= models.IntegerField(null=True)
    DC_OES= models.IntegerField(null=True)
    HH_OES= models.IntegerField(null=True)
    DC_OF= models.IntegerField(null=True)
    HH_OF= models.IntegerField(null=True)
    DC_JUTP= models.IntegerField(null=True)
    HH_JUTP= models.IntegerField(null=True)
    DC_IG= models.IntegerField(null=True)
    HH_IG= models.IntegerField(null=True)
    DC_OR= models.IntegerField(null=True)
    HH_OR= models.IntegerField(null=True)
    DC_DIR_SOST= models.IntegerField(null=True)
    HH_DIR_SOST= models.IntegerField(null=True)
    DC_TP_SOST= models.IntegerField(null=True)
    HH_TP_SOST= models.IntegerField(null=True)
    DC_SUP_SOST= models.IntegerField(null=True)
    HH_SUP_SOST= models.IntegerField(null=True)
    DC_SUBDIR= models.IntegerField(null=True)
    HH_SUBDIR= models.IntegerField(null=True)
    DC_PROF_ENC= models.IntegerField(null=True)
    HH_PROF_ENC= models.IntegerField(null=True)
    DC_EDUC_TRAD= models.IntegerField(null=True)
    HH_EDUC_TRAD= models.IntegerField(null=True)
    DC_TOT= models.IntegerField(null=True)
    HH_TOT= models.IntegerField(null=True)

class rendimiento_academico(models.Model):

    AGNO= models.IntegerField()
    RBD= models.IntegerField(null=True)
    NOM_RBD= models.CharField(null=True)
    COD_REG_RBD= models.IntegerField(null=True)
    COD_PRO_RBD= models.IntegerField(null=True)
    COD_COM_RBD= models.IntegerField(null=True)
    NOM_COM_RBD= models.CharField(null=True)
    COD_DEPE2= models.IntegerField(null=True)
    COD_DEPE= models.IntegerField(null=True)
    RURAL_RBD= models.IntegerField(null=True)
    GEN_ALU= models.IntegerField(null=True)
    MRUN= models.IntegerField(null=True)
    EDAD_ALU= models.IntegerField(null=True)
    NOM_COM_ALU= models.CharField(null=True)
    COD_JOR= models.IntegerField(null=True)
    PROM_GRAL= models.IntegerField(null=True)
    ASISTENCIA= models.IntegerField(null=True)
    SIT_FIN_R= models.IntegerField(null=True)